micronaut:
  application:
    name: recimporter
netty:
  default:
    allocator:
      max-order: 3
processing:
  system:
    url: 'consumed.api.URL'
recordings:
  location: 'location of recorded calls'
logger:
  levels:
    ROOT: DEBUG
